version: '3.8'

services:
  wedding-rsvp:
    build: .
    container_name: wedding-rsvp-easypanel
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET:-default-secret-change-in-production}
    volumes:
      # Volume absoluto para o banco de dados - ESSENCIAL para persistência
      - /var/lib/easypanel/data/wedding-rsvp/database:/app/wedding_rsvp.db
      # Volume absoluto para uploads
      - /var/lib/easypanel/data/wedding-rsvp/uploads:/app/public/uploads
      # Volume absoluto para logs
      - /var/lib/easypanel/data/wedding-rsvp/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# IMPORTANTE: No Easypanel, certifique-se de que estes diretórios existam
# e tenham as permissões corretas antes de fazer o deploy
